l_english:
 EU4DISPLAYNAME: "Europa Universalis IV to Victoria 3"
 EU4GAME: "Europa Universalis IV"
 VIC3GAME: "Victoria 3"
 EU4FOLDER: "Europa Universalis IV Install Directory"
 EU4FOLDERTIP: "The path on your computer where Europa Universalis IV is installed"
 EU4DOC: "Europa Universalis IV Documents Directory"
 EU4DOCTIP: "A path on your computer where Europa Universalis IV keeps temporary files"
 VIC3FOLDER: "Victoria 3 Install Directory"
 VIC3FOLDERTIP: "The path on your computer where Victoria 3 is installed"
 VIC3MOD: "Victoria 3 Mod Directory"
 VIC3MODTIP: "The path on your computer where Victoria 3 stores mods"
 EU4FILE: "Path to the converter executable"
 EU4FILETIP: "Path to EU4ToVic3Converter.exe"
 EU4SAVE: "Path to the EU4 savegame"
 EU4SAVETIP: "Path to your savegame from EU4"
