l_russian:
 EU4DISPLAYNAME: "из Европы Универсалис IV в Викторию 3"
 EU4GAME: "Европа Универсалис IV"
 VIC3GAME: "Виктория 3"
 EU4FOLDER: "Европа Универсалис IV Установить каталог"
 EU4FOLDERTIP: "Путь на вашем компьютере, где установлена Европа Универсалис IV"
 EU4DOC: "Справочник документов Европа Универсалис IV"
 EU4DOCTIP: "Путь на вашем компьютере, где Европа Универсалис IV хранит временные файлы"
 VIC3FOLDER: "Установочный каталог Виктория 3"
 VIC3FOLDERTIP: "Путь на вашем компьютере, где установлена Виктория 3"
 VIC3MOD: "Виктория 3 Мод Каталог"
 VIC3MODTIP: "Путь на вашем компьютере, где хранятся моды Виктория 3"
 EU4FILE: "Путь к исполняемому файлу конвертера"
 EU4FILETIP: "Путь к EU4ToVic3Converter.exe"
 EU4SAVE: "Путь к сохранению игры EU4"
 EU4SAVETIP: "Путь к вашей сохраненной игре из EU4"
