version: dev.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
build_script:
- cmd: >-
    git submodule update --init --recursive

    msbuild -m EU4ToVic3.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- ps: >-
    cd Release-Tests
    
    .\EU4ToV3Tests.exe --gtest_output=xml:tests.xml
    
    (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))   
artifacts:
- path: Release
  name: EU4toVic3-0.1Adams
deploy:
- provider: GitHub
  release: windows_development_build
  description: The most recent build of the development version
  auth_token:
    secure: LBJzs4y9j0N5y0ajp7gmVk3Pvnec1UU5pTCdIMbQYUddEXQnWTJ79FXsd9SCs7YQ
  repository: paradoxGameConverters/EU4ToVic3
  artifact: EU4toVic3-0.1Adams
  prerelease: true
  force_update: true
- provider: GitHub
  tag: 0.1A
  release: 0.1 Adams - for EU4[1.31] and Vic3[1.0] 
  auth_token:
    secure: LBJzs4y9j0N5y0ajp7gmVk3Pvnec1UU5pTCdIMbQYUddEXQnWTJ79FXsd9SCs7YQ
  repository: paradoxGameConverters/EU4ToVic3
  artifact: EU4ToVic3-0.1Adams
