l_latin:
 EU4DISPLAYNAME: "ex Europa Universali ad Victoriam 3"
 EU4GAME: "Europa Universalis IV"
 VIC3GAME: "Victoria 3"
 EU4FOLDER: "Scapus locationis Europae Universalis IV"
 EU4FOLDERTIP: "Via in qua locatus est ludus Europa Universalis IV"
 EU4DOC: "Scapus documentorum Europae Universalis IV"
 EU4DOCTIP: "Via in qua Europa Universalis IV scribit fasciculos temporales"
 VIC3FOLDER: "Scapus locationis Victoriae 3"
 VIC3FOLDERTIP: "Via in qua locatus est ludus Victoria 3"
 VIC3MOD: "Scapus correctionum Victoriae 3"
 VIC3MODTIP: "Via in qua locatae sunt correctiones Victoriae 3"
 EU4FILE: "Via programmatis"
 EU4FILETIP: "Via ad EU4ToVic3Converter.exe"
 EU4SAVE: "Via ad conditum EU4"
 EU4SAVETIP: "Via ad conditum EU4"
