l_italian:
 EU4DISPLAYNAME: "da Europa Universalis IV a Victoria 3"
 EU4GAME: "Europa Universalis IV"
 VIC3GAME: "Victoria 3"
 EU4FOLDER: "Cartella di installazione di Europa Universalis IV"
 EU4FOLDERTIP: "Il percorso in cui è installato Europa Universalis IV"
 EU4DOC: "Cartella dei documenti di Europa Universalis IV"
 EU4DOCTIP: "Un percorso in cui Europa Universalis IV conserva file temporanei"
 VIC3FOLDER: "Cartella di installazione di Victoria 3"
 VIC3FOLDERTIP: "Il percorso in cui è installato Victoria 3"
 VIC3MOD: "Cartella delle mod per Victoria 3"
 VIC3MODTIP: "Il percorso in cui Victoria 3 memorizza le mod"
 EU4FILE: "Percorso dell'eseguibile del convertitore"
 EU4FILETIP: "Percorso di EU4ToVic3Converter.exe"
 EU4SAVE: "Percorso per il savegame EU4"
 EU4SAVETIP: "Percorso per il tuo savegame da EU4"
