l_german:
 EU4DISPLAYNAME: "von Europa Universalis IV zu Victoria 3"
 EU4GAME: "Europa Universalis IV"
 VIC3GAME: "Victoria 3"
 EU4FOLDER: "Europa Universalis IV-Installationsverzeichnis"
 EU4FOLDERTIP: "Der Pfad auf Ihrem Computer, auf dem Europa Universalis IV installiert ist"
 EU4DOC: "Europa Universalis IV-Dokumentenverzeichnis"
 EU4DOCTIP: "Ein Pfad auf Ihrem Computer, in dem Europa Universalis IV temporäre Dateien speichert"
 VIC3FOLDER: "Victoria 3-Installationsverzeichnis"
 VIC3FOLDERTIP: "Der Pfad auf Ihrem Computer, auf dem Victoria 3 installiert ist"
 VIC3MOD: "Victoria 3 Mod-Verzeichnis"
 VIC3MODTIP: "Der Pfad auf Ihrem Computer, auf dem Victoria 3 Mods speichert"
 EU4FILE: "Pfad zur ausführbaren Datei des Konverters"
 EU4FILETIP: "Pfad zu EU4ToVic3Converter.exe"
 EU4SAVE: "Pfad zum EU4-Savegame"
 EU4SAVETIP: "Pfad zu Ihrem Savegame von EU4"
