name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'EU4ToVic3/Source'
          - 'EU4ToVic3Tests'
    steps:
    - uses: actions/checkout@v5
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: '20'
        check-path: ${{ matrix.path }}