name: Build, test
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
jobs:
   build_and_test:
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Init submodules"
      run: |
       git submodule update --init --recursive
    - name: "Build solution"
      run: |
       cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\"
       .\MSBuild.exe -m -p:Configuration=Release $Env:GITHUB_WORKSPACE\EU4toVic3.sln
    - name: "Run tests"
      run: |
       cd $Env:GITHUB_WORKSPACE\Release-Tests\
       .\EU4toV3Tests.exe
    - name: "Cleanup"
      run: |
        Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Recurse -Force | Remove-Item -force -recurse
        Remove-Item $Env:GITHUB_WORKSPACE -Force 

